name: Pull go image and run

on:
  workflow_dispatch:
    inputs:
      tags:
        description: Some boolean field
        required: false
        type: boolean

jobs:
  build:
    strategy: 
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04]
        version: [1.15, 1.16, 1.17]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Pull the self created image from dockerhub
        run: docker pull ${{ secrets.DOCKERHUB_USERNAME }}/go_image

      - name: Run the pulled image
        run: docker run ${{ secrets.DOCKERHUB_USERNAME }}/go_image:latest
