name: Push go image

on:
  workflow_dispatch:
    inputs:
      tags:
        description: Some boolean field
        required: false
        type: boolean

jobs:
  build:
    strategy: 
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04]
        version: [1.15, 1.16, 1.17]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up Dockere Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          build-args: |
            VERSION=${{ matrix.version }}
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/go_image:latest

